## This is basic continuous integration build for your Quarkus application.

name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Checkout GeoServer
        uses: actions/checkout@v3
        with:
          repository: geoserver/geoserver
          ref: 2.20.6
          path: './geoserver'
      - name: Build web-service-auth
        working-directory: ./geoserver/src/community/web-service-auth
        run: mvn clean package -DskipTests=true
      - name: PWD
        run: pwd
      - name: Copy Overlay Resources
        run: cp ./geoserver/src/community/web-service-auth/target/*.jar /resources/overlays/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and Push the Container Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: umeraltaf/aurin-geoserver:2.20.6