## This is basic continuous integration build for your Quarkus application.

name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Checkout GeoServer
#        uses: actions/checkout@v3
#        with:
#          repository: geoserver/geoserver
#          ref: 2.20.6
#          path: './geoserver'
#      - name: Build web-service-auth
#        working-directory: ./geoserver/src/community/web-service-auth
#        run: mvn clean package -DskipTests=true
#      - name: PWD
#        run: pwd
#      - name: Copy Overlay Resources
#        run: mkdir -p ./resources/overlays/usr/local/tomcat/webapps/geoserver/WEB-INF/lib && cp ./geoserver/src/community/web-service-auth/target/*.jar ./resources/overlays/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/
#      - name: Clean GeoServer Source Dir
#        run: rm -rf geoserver
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Source .env
        run: source .env
#      - name: Build Docker Image
#        run: sudo docker compose -f docker-compose-build.yml build
      - name: Build and Push the Container Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: umeraltaf/aurin-geoserver:2.20.6
          build-args: |
            IMAGE_VERSION=${IMAGE_VERSION}
            JAVA_HOME=${IMAGE_VERSION}
            GS_VERSION=${IMAGE_VERSION}
            WAR_URL=${IMAGE_VERSION}
            DOWNLOAD_ALL_STABLE_EXTENSIONS=${IMAGE_VERSION}
            DOWNLOAD_ALL_COMMUNITY_EXTENSIONS=${IMAGE_VERSION}
            STABLE_PLUGIN_BASE_URL=${IMAGE_VERSION}