## This is basic continuous integration build for your Quarkus application.

name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Checkout GeoServer
        uses: actions/checkout@v3
        with:
          name: geoserver/geoserver
          ref: 2.20.6
          path: './geoserver'
      - name: Build web-service-auth
        run: mvn clean package -DskipTests=true
