name: Build

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout GeoServer
        uses: actions/checkout@v3
        with:
          repository: geoserver/geoserver
          ref: 2.21.2
          path: './geoserver'
      - name: Build web-service-auth
        working-directory: ./geoserver/src/community/web-service-auth
        run: mvn clean package -DskipTests=true
      - name: PWD
        run: pwd
      - name: Copy Overlay Resources
        run: mkdir -p ./resources/overlays/usr/local/tomcat/webapps/geoserver/WEB-INF/lib && cp ./geoserver/src/community/web-service-auth/target/*.jar ./resources/overlays/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/
      - name: Update Dockerfile to copy in custom resources
        run: |
          echo "COPY custom_resources /custom_resources >> scripts/start.sh
      - name: Update start.sh script for custom resources
        run: |
          echo "chmod +x /custom_resources/copy_custom_resources.sh" >> scripts/start.sh
          echo "/custom_resources/copy_custom_resources.sh" >> scripts/start.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build Docker Image
        run: sudo docker compose -f docker-compose-build.yml build
      - name: Tag Image
        run: docker image tag kartoza/geoserver:2.21.2 umeraltaf/geoserver:2.21.2
      - name: Push to Repo
        run: docker image push umeraltaf/geoserver:2.21.2