name: Test

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Runner
        run: lscpu
      - name: load var
        run: cat .env >> $GITHUB_ENV
      - name: echo var
        run:       echo "${{ env.GS_VERSION }}"